//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTripEntities1 : DbContext
    {
        public DBTripEntities1()
            : base("name=DBTripEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Area> Areas { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<CityzenType> CityzenTypes { get; set; }
        public DbSet<Day> Days { get; set; }
        public DbSet<OpenHour> OpenHours { get; set; }
        public DbSet<Price> Prices { get; set; }
        public DbSet<RecomendedRoute> RecomendedRoutes { get; set; }
        public DbSet<Site> Sites { get; set; }
        public DbSet<RouteNumbering> RouteNumberings { get; set; }
    }
}
