//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenHour
    {
        public int OpenHoursID { get; set; }
        public Nullable<System.TimeSpan> OpenHour1 { get; set; }
        public Nullable<System.TimeSpan> CloseHour { get; set; }
        public int SiteID { get; set; }
        public int DayID { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual Site Site { get; set; }
    }
}
