//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int PriceID { get; set; }
        public int Price1 { get; set; }
        public int SiteID { get; set; }
        public int CityzenTypeID { get; set; }
    
        public virtual CityzenType CityzenType { get; set; }
        public virtual Site Site { get; set; }
    }
}
