//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecomendedRoute
    {
        public RecomendedRoute()
        {
            this.RouteNumberings = new HashSet<RouteNumbering>();
        }
    
        public int RouteID { get; set; }
        public string RouteName { get; set; }
        public System.TimeSpan AvgRouteTime { get; set; }
        public int Difficulty { get; set; }
        public string RoutePicture { get; set; }
    
        public virtual ICollection<RouteNumbering> RouteNumberings { get; set; }
    }
}
