//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteNumbering
    {
        public int RouteID { get; set; }
        public int SiteID { get; set; }
        public int NumInRoute { get; set; }
        public int RouteNumberID { get; set; }
    
        public virtual RecomendedRoute RecomendedRoute { get; set; }
        public virtual Site Site { get; set; }
    }
}
