//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.OpenHours = new HashSet<OpenHour>();
            this.Prices = new HashSet<Price>();
            this.RouteNumberings = new HashSet<RouteNumbering>();
        }
    
        public int SiteID { get; set; }
        public string Name { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public Nullable<bool> InDoor { get; set; }
        public Nullable<bool> OutDoor { get; set; }
        public Nullable<bool> Accessibility { get; set; }
        public string AvgStayTime { get; set; }
        public string WebSite { get; set; }
        public int AreaID { get; set; }
        public int CategoryID { get; set; }
        public string SitePicture { get; set; }
        public double Lat { get; set; }
        public double Lon { get; set; }
        public string About { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<OpenHour> OpenHours { get; set; }
        public virtual ICollection<Price> Prices { get; set; }
        public virtual ICollection<RouteNumbering> RouteNumberings { get; set; }
    }
}
